### ISSUE TITLE
Problem building on linux

### ISSUE THREAD

**Issue by KismetPartisan** [vcoda/magma#6]
I'm trying to build the library on archlinux, but I'm getting this error:
`src/misc/deviceFaultInfo.cpp: In copy constructor ‘magma::DeviceFaultInfo::DeviceFaultInfo(const magma::DeviceFaultInfo&)’:
src/misc/deviceFaultInfo.cpp:63:5: error: ‘strcpy_s’ was not declared in this scope; did you mean ‘strcpy’?
   63 |     strcpy_s(description, VK_MAX_DESCRIPTION_SIZE, other.description);
      |     ^~~~~~~~
      |     strcpy`
From my understanding, strcpy_s is a windows only function.

**Comment by vcoda** [comment]
Hi @KismetPartisan !
Thank you for pointing this issue. On Linux setup I used a bit outdated Vulkan SDK because newer ones have issues with GLIBC_2.29 not found on my setup. This older SDK doesn't defined VK_EXT_device_fault extension, so I missed this error. I replaced call of strcpy_s() with my own cross-platform function.
